### PR TITLE
[BUGFIX] continue command when processed file is missing

### LINKED ISSUE #43: Errors when processed file is missing
The scheduler task throws an error when a processed file is missing. This should probably just be ignored since the processed file record is deleted anyways?
https://github.com/sourcebroker/imageopt/blob/601e3d30424f8ed957893b8ceaf9f2e22eced322/Classes/Service/OptimizeImagesFalService.php#L134
missing-processed-file

I also get  this error in the CliDisplayUtility which stops the execution of the command
```
[ ErrorReporting\Warning ]       
 Warning: Undefined array key ""
```

The errors happen in TYPO3 11.5.26 with PHP 8.1 with MySQL 8.0

### PR DESCRIPTION
**Pull request by akiessling**
Fixes #43

### CODE REVIEW

**Comment by akiessling** [comment]
I just saw that not all size_before and size_after are int fields. Is that intentional? I needed to set the default values to 0 to fix my sql errors.

**Comment by kszymukowicz** [comment]
Actually TYPO3 database update schema do not like int and default null value so I normalised all sizes to varchar.
Can you please test if with current master branch you still have problems?

**Comment by akiessling** [comment]
I think it looks god now. I had to reset my processed images anyways due to some other errors, thus running the task shows no errors now.

**Comment by akiessling** [comment]
Thanks for taking care!

**Pull request closed without merging**
